{% set name = "lux-widget" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lux-widget-{{ version }}.tar.gz
  sha256: 7b5fdb63a240acc9d61da1fe2c1085f1f65768bcbdfe7ead5e3097afa9ac72a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ipywidgets >=7.5.0
    - jupyter
    - pip
    - python >=3.6
  run:
    - ipywidgets >=7.5.0
    - jupyter
    - python >=3.6

test:
  imports:
    - luxwidget
    - luxwidget.nbextension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lux-org/lux-widget
  summary: Jupyter Widget for Intelligent Data Discovery
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dorisjlee
